# Generated by Django 3.2.8 on 2022-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycloneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclone_name', models.CharField(blank=True, help_text='Enter cyclone name', max_length=50, null=True)),
                ('intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4'), (5, 'Category 5')], default=1, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('origin_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
