# Generated by Django 3.2.8 on 2022-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclonedata',
            name='category',
            field=models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4'), (5, 'Category 5')], default=1),
        ),
    ]
