# Generated by Django 3.2.8 on 2022-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0002_alter_cyclonedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclonedata',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cyclonedata',
            name='intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyclonedata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyclonedata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
