# Generated by Django 3.2.8 on 2022-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0003_auto_20220209_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormData',
            fields=[
                ('storm_id', models.AutoField(primary_key=True, serialize=False)),
                ('storm_name', models.CharField(blank=True, help_text='Enter cyclone name', max_length=50, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4'), (5, 'Category 5')], default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('origin_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['storm_name', '-origin_date'],
            },
        ),
        migrations.DeleteModel(
            name='CycloneData',
        ),
    ]
