# Generated by Django 3.2.8 on 2022-02-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0004_auto_20220209_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdata',
            options={'ordering': ['storm_name', '-date']},
        ),
        migrations.RenameField(
            model_name='stormdata',
            old_name='origin_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='stormdata',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tropical Depression'), (2, 'Tropical Storm'), (3, 'Category 1'), (4, 'Category 2'), (5, 'Category 3'), (6, 'Category 4'), (7, 'Category 5')], default=1),
        ),
        migrations.CreateModel(
            name='StormTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('storm_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intensity_app.stormdata')),
            ],
        ),
    ]
