# Generated by Django 3.2.8 on 2022-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0006_auto_20220224_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormdata',
            name='storm_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
