# Generated by Django 3.2.8 on 2022-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0007_alter_stormdata_storm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormtrack',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
