# Generated by Django 3.2.8 on 2022-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0008_alter_stormtrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormtrack',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tropical Depression'), (2, 'Tropical Storm'), (3, 'Category 1'), (4, 'Category 2'), (5, 'Category 3'), (6, 'Category 4'), (7, 'Category 5')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='category_labels',
            field=models.IntegerField(choices=[(1, 'Tropical Depression'), (2, 'Tropical Storm'), (3, 'Category 1'), (4, 'Category 2'), (5, 'Category 3'), (6, 'Category 4'), (7, 'Category 5')], default=1, null=True),
        ),
    ]
