# Generated by Django 3.2.8 on 2022-02-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0009_auto_20220225_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stormtrack',
            name='category_labels',
        ),
    ]
