# Generated by Django 3.2.8 on 2022-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0010_remove_stormtrack_category_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdata',
            options={'ordering': ['-storm_id', 'storm_name']},
        ),
        migrations.RemoveField(
            model_name='stormtrack',
            name='category',
        ),
        migrations.AddField(
            model_name='stormdata',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tropical Depression'), (2, 'Tropical Storm'), (3, 'Category 1'), (4, 'Category 2'), (5, 'Category 3'), (6, 'Category 4'), (7, 'Category 5')], default=1),
        ),
        migrations.AlterField(
            model_name='stormdata',
            name='storm_name',
            field=models.CharField(help_text='Enter cyclone name', max_length=50),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='intensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='labels',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stormtrack',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
